trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'd7fbd141-a858-4611-bc41-283c0ce8473f'
  imageRepository: 'luniemmaspringpetclinicaksproject'
  containerRegistry: 'emmacontainer2024.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'emmacontainer20245918-auth'
  vmImageName: 'windows-latest'  # Changed to use latest Windows Server image
  k8sNamespaceForPR: 'review-app-$(System.PullRequest.PullRequestId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    