apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic
  labels:
    app: clinic
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1727878910416
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic
  template:
    metadata:
      labels:
        app: clinic
    spec:
      containers:
        - name: clinic
          image: springbootclinic.azurecr.io/image-workflow-1727878910416:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
