apiVersion: v1
kind: Service
metadata:
  name: clinic
  namespace: namespace-workflow-1727878910416
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: clinic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080